api_version = "2026-04"

[[extensions]]
name = "t:name"
handle = "merge-print-addons"
type = "function"
uid = "31d645b1-6987-9c1e-e402-e30164c28444f4415cce"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
